export type TCARDS = {
  "2c": string;
  "3c": string;
  "4c": string;
  "5c": string;
  "6c": string;
  "7c": string;
  "8c": string;
  "9c": string;
  "10c": string;
  Jc: string;
  Qc: string;
  Kc: string;
  Ac: string;
  "2b": string;
  "3b": string;
  "4b": string;
  "5b": string;
  "6b": string;
  "7b": string;
  "8b": string;
  "9b": string;
  "10b": string;
  Jb: string;
  Qb: string;
  Kb: string;
  Ab: string;
  "2h": string;
  "3h": string;
  "4h": string;
  "5h": string;
  "6h": string;
  "7h": string;
  "8h": string;
  "9h": string;
  "10h": string;
  Jh: string;
  Qh: string;
  Kh: string;
  Ah: string;
  "2p": string;
  "3p": string;
  "4p": string;
  "5p": string;
  "6p": string;
  "7p": string;
  "8p": string;
  "9p": string;
  "10p": string;
  Jp: string;
  Qp: string;
  Kp: string;
  Ap: string;
};

export type TCard = keyof TCARDS;

export type TTOKENS = {
  "1": string;
  "5": string;
  "10": string;
  "25": string;
  "100": string;
  "500": string;
};
export type TToken = keyof TTOKENS;
